---
title: "Cálculo del Índice con Netica"
description: |
  Ejercicio que ejemplifica la obtención de los valores del índice con Netica.
author:
  - name: Octavio Pérez Maqueo y Miguel Equihua Zamora
    url: {}
date: 2022-08-30
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
En este video se explica la forma de utilizar Netica que es un programa comercial para el diseño y entrenamiento de redes bayesianas.  Lo utilizamos para construir y entrenar la red bayesiana que utilizamos para producir las estimaciones del _índice de integridad ecosistémica_ que hicimos para valorar la condición de los ecosistemas de México. En el video se muestra como hacer los cálculos para el caso particular del estado de Yucatán, sólo como una forma de ejercitar con un conjunto relativamente pequeño de datos. Las mismas operaciones y lógica se aplica al caso general que usamos para obtener los estimadores do todo el país. El objetivo que proponemos para esta participación es:

> El participante se familiariza con las operaciones y lógica de cómputo involucradas en la generación de los estimadores del índice de integridad ecosistémica, tal y como se aplicó el enfoque en el piloto mexicano


<iframe width="969" height="545" src="https://www.youtube.com/embed/W5esQJeQ_oE" title="Red Bayesiana del Índice de Integridad Ecosistémica con Netica" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

